import type { GetServerSideProps, NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { useState } from "react";
import {
  GetPokemonByNameDocument,
  GetPokemonByNameQuery,
  GetPokemonByNameQueryVariables,
  Pokemon,
  PokemonEnum,
  usePokemonsQuery,
} from "../components/pokemon-urql";
import { getPokeByName } from "../services/gql";
import styles from "../styles/Home.module.css";

const Home: NextPage<{
  poke?: GetPokemonByNameQuery["getPokemon"];
  defaultName: string;
}> = ({ defaultName = "", poke }) => {
  const [name, setName] = useState(defaultName);
  const [r] = usePokemonsQuery({ variables: { name } });
  const pokes = r.data?.getFuzzyPokemon;

  return (
    <div className={styles.container}>
      <Head>
        <title>We Do Pokemon</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>{pokes?.length}</h1>
      <input
        value={name}
        type="text"
        onChange={(e) => setName(e.target.value)}
      ></input>
      <main className={styles.main}>
        {pokes?.map((i) => {
          return <div key={i?.key}>{i?.key}</div>;
        })}
      </main>
      <div>{poke?.height}</div>

      <footer className={styles.footer}></footer>
    </div>
  );
};

export const getServerSideProps: GetServerSideProps = async (context) => {
  let poke: GetPokemonByNameQuery["getPokemon"] | undefined;
  if (Object.values(PokemonEnum).includes(context?.query.name as PokemonEnum)) {
    poke = await getPokeByName({ pokemon: context.query.name as PokemonEnum });
  }

  return {
    props: { poke, pokes: [], defaultName: context?.query?.name }, // will be passed to the page component as props
  };
};

export default Home;
